# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: claims/claims.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'claims/claims.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63laims/claims.proto\x12\x06\x63laims\" \n\x0c\x43laimRequest\x12\x10\n\x08\x63laim_id\x18\x01 \x01(\t\"2\n\rClaimResponse\x12\x10\n\x08\x63laim_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32K\n\rClaimsService\x12:\n\x0bSubmitClaim\x12\x14.claims.ClaimRequest\x1a\x15.claims.ClaimResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'claims.claims_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLAIMREQUEST']._serialized_start=31
  _globals['_CLAIMREQUEST']._serialized_end=63
  _globals['_CLAIMRESPONSE']._serialized_start=65
  _globals['_CLAIMRESPONSE']._serialized_end=115
  _globals['_CLAIMSSERVICE']._serialized_start=117
  _globals['_CLAIMSSERVICE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
