# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import claims_pb2 as claims_dot_claims__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in claims/claims_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ClaimsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitClaim = channel.unary_unary(
            "/claims.ClaimsService/SubmitClaim",
            request_serializer=claims_dot_claims__pb2.ClaimRequest.SerializeToString,
            response_deserializer=claims_dot_claims__pb2.ClaimResponse.FromString,
            _registered_method=True,
        )


class ClaimsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ClaimsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SubmitClaim": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitClaim,
            request_deserializer=claims_dot_claims__pb2.ClaimRequest.FromString,
            response_serializer=claims_dot_claims__pb2.ClaimResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "claims.ClaimsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("claims.ClaimsService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ClaimsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitClaim(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/claims.ClaimsService/SubmitClaim",
            claims_dot_claims__pb2.ClaimRequest.SerializeToString,
            claims_dot_claims__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
