# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eligibility.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'eligibility.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65ligibility.proto\x12\x0b\x65ligibility\"(\n\x12\x45ligibilityRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\"9\n\x13\x45ligibilityResponse\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2m\n\x12\x45ligibilityService\x12W\n\x10\x43heckEligibility\x12\x1f.eligibility.EligibilityRequest\x1a .eligibility.EligibilityResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eligibility_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELIGIBILITYREQUEST']._serialized_start=34
  _globals['_ELIGIBILITYREQUEST']._serialized_end=74
  _globals['_ELIGIBILITYRESPONSE']._serialized_start=76
  _globals['_ELIGIBILITYRESPONSE']._serialized_end=133
  _globals['_ELIGIBILITYSERVICE']._serialized_start=135
  _globals['_ELIGIBILITYSERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
