"""Initial schema

Revision ID: bdaa1a998ae5
Revises: 
Create Date: 2025-05-04 16:38:20.222042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdaa1a998ae5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_records',
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('patient_dob', sa.Date(), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('imported_from', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('raw_code', sa.String(), nullable=True),
    sa.Column('raw_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('procedure_code', sa.String(), nullable=True),
    sa.Column('charge_amount', sa.Float(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_lines')
    op.drop_table('claim_events')
    op.drop_table('claims')
    op.drop_table('claim_records')
    # ### end Alembic commands ###
